### ISSUE TITLE
Right click for opening first link?

### ISSUE THREAD

**Issue by michaelsjackson** [novoid/org-du#1]
Thanks for sharing this cool tool.  Would it be possible, opening some link to a file (e.g. pdf document) or a link with a right click?  It could take simply the first file or web link it finds in that section.  This could give another dimension to this little tool, not only for navigating around, but also opening some document, could be useful in lecture scenarios, where you dive into some deeper levels, then opening some presentation/lecture data.

Everyone would still have an overview where they are, as they navigated around together.

**Comment by novoid** [comment]
Hi,
In short: no.
First, I'm not the author of [xdu](https://directory.fsf.org/wiki/XDU). So you'd have to place your feature request (which I totally understand) at their project's system. Secondly, I'm mis-using xdu. The original xdu is used not with Org mode files as input but with the output of the UNIX/Linux tool `du` for disk usage. This is why they probably won't support your feature request because xdu is not meant to open a file. It deals with directories.
I hope I could explain why you won't see this feature within this project.

**Comment by michaelsjackson** [comment]
Yeah, thanks, I know you are misusing it in a "hackey way" which is cool. Maybe in future some other similar tool might appear with link triggering support, then those nice overviews could get a life behind it (the link contents).

**Comment by novoid** [comment]
Hi @michaelsjackson,

Your idea resulted in some thinking on my side today. I did my best to write a convincing argument to extend `xdu`. You can see it on https://github.com/vlasovskikh/xdu/issues/1

It's not exactly your requirement but a huge step closer to a `xdu` implementation that makes it possible to realize your requirement as well.

It'd be cool when you're able to push the issue by adding some kind of thumbs-up or similar and probably do some advertisement for the idea since the repository does not seem to be active or well-known. The more people are confronted with the idea, the more likely it is that somebody starts implementing.
